//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineWarehousingInformationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int staffID { get; set; }
        public int userID { get; set; }
        public int warehouseID { get; set; }
        public string title { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
